# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170620_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
